[theme]
# Streamlit Community Cloudのテーマ設定
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[server]
# サーバー設定
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
# ブラウザ設定
gatherUsageStats = false
